/**redux 状态文件 **/

export const TEST_OFF_OR_ON = {
  OFF: "TEST_OFF",
  ON: "TEST_ON",
  REQUEST: "TEST_START",
  SUCCESS: "TEST_COMPLIT",
  FAILURE: "TEST_ING"
};
export const PROCESS = {
  REQUEST: "PROCESS_START",
  SUCCESS: "PROCESS_COMPLIT",
  FAILURE: "PROCESS_ING",
};